# Generated by Django 5.0 on 2025-07-07 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questpaper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prospectors',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='questionpaper',
            options={'managed': False},
        ),
    ]
