# Generated by Django 5.0 on 2025-07-07 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questpaper', '0002_alter_prospectors_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='prospectors',
            table='questpaper_prospectors',
        ),
        migrations.AlterModelTable(
            name='questionpaper',
            table='questpaper_questionpaper',
        ),
    ]
