# Generated by Django 5.0 on 2025-07-07 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bursary', '0002_alter_bursary_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bursary',
            table='bursary_bursary',
        ),
    ]
