# Generated by Django 5.0 on 2025-07-07 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_alter_collegeanduniversities_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='collegeanduniversities',
            table='college_collegeanduniversities',
        ),
    ]
