# Generated by Django 5.0 on 2025-07-01 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='circuit',
        ),
        migrations.RemoveField(
            model_name='circuit',
            name='department_by',
        ),
        migrations.RemoveField(
            model_name='circuit',
            name='educators_on_db',
        ),
        migrations.RemoveField(
            model_name='circuit',
            name='learners_on_db',
        ),
        migrations.RemoveField(
            model_name='circuit',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='circuit',
            name='principals_on_db',
        ),
        migrations.RemoveField(
            model_name='circuit',
            name='province',
        ),
        migrations.RemoveField(
            model_name='circuit',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='circuit',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='circuit',
            name='staff_on_db',
        ),
        migrations.RemoveField(
            model_name='circuit',
            name='website_url',
        ),
        migrations.RemoveField(
            model_name='circuit',
            name='year',
        ),
        migrations.AddField(
            model_name='educator',
            name='circuit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.circuit'),
        ),
        migrations.AddField(
            model_name='principal',
            name='circuit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.circuit'),
        ),
        migrations.AddField(
            model_name='student',
            name='circuit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.circuit'),
        ),
        migrations.AlterField(
            model_name='circuit',
            name='email',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='circuit',
            name='whatsapp_number',
            field=models.CharField(default=4, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='circuit_manager',
            name='circuit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.circuit'),
        ),
        migrations.AlterField(
            model_name='school',
            name='circuit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main_app.circuit'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
