# Generated by Django 5.0 on 2025-07-07 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_appointment_circuit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsandevents',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='prospectors',
            options={'managed': False},
        ),
    ]
