# Generated by Django 5.0 on 2025-07-07 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_newsandevents_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='newsandevents',
            table='news_newsandevents',
        ),
        migrations.AlterModelTable(
            name='prospectors',
            table='bursary_prospectors',
        ),
    ]
