# Generated by Django 5.0 on 2025-07-09 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_newsandevents_table_alter_prospectors_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='newsandevents',
            table='main_app_newsandevents',
        ),
        migrations.AlterModelTable(
            name='prospectors',
            table='main_app_prospectors',
        ),
    ]
