# Generated by Django 5.0 on 2025-07-09 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_newsandevents_table_alter_prospectors_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'managed': False},
        ),
    ]
