# Generated by Django 5.0 on 2025-07-09 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_document_paperrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('question_type', models.CharField(choices=[('career', 'Career Guidance'), ('school', 'School Management'), ('prospector', 'Undergraduate Prospector'), ('bursary', 'Bursaries/Financial Aid'), ('assessment', 'Assessments/Homework'), ('memorandum', 'Memorandums/Answer Keys'), ('general', 'General Question')], max_length=50)),
                ('question', models.TextField()),
                ('response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
